version: '3'

services:
  mysql-db:
    container_name:  mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_DATABASE: test_nestjs_db
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d/
      - ./mysql-data:/var/lib/mysql
    networks:
      - devops-api

  react-app-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
    networks:
      - devops-api
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-container-api
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4041:4041
    networks:
      - devops-api
networks:
  devops-api:
    driver: bridge