version: '3'

services:
  mysql-db:
    container_name:  mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_DATABASE: react_cv_db
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d/
      - C:/Users/LENOVO/Desktop/tp/react/minprojet/mysql-data:/var/lib/mysql
    networks:
      - devops_api
  react-app-api:
    image: nest_api_react
    container_name:  nest_api_react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
    networks:
      - devops_api
networks:
  devops_api:
    name: devops_api
    driver: bridge